#!/bin/bash

for file in ./files/*; do
    if [ -f "$file" ]; then
        name=$(basename "$file")
        first=${name:0:1}
        lower=$(echo "$first" | tr '[:upper:]' '[:lower:]')

        if [ -d "./$lower" ]; then
            mv "$file" "./$lower/"
        fi
    fi
done